title: Red Hills Iagon
email: info@rockinghat.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
domain: "redhills.rockinghat.com"
url: "https://redhills.rockinghat.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RockingHatLLC
github_username:  rockinghat

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

destination: docs/

keep_files:
  - CNAME
